name: Lint
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install packages
      uses: actions/setup-node@v1
    - run: npm ci
    - run: npm run lint
      env:
        CI: true
