name: Javascript tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Testing code
      uses: actions/setup-node@v1
      run: |
        npm ci
        npm run lint
        npm run test
