name: Ava Test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install packages
      uses: actions/setup-node@v1

    - run: npm ci
    - run: npm run test
    - run: npm test
